
export const PRIMARY_COLOR       = '#FF7954'
export const PRIMARY_LIGHT_COLOR = '#FFE4DD'
export const ORANGE_COLOR        = '#DA5203'
export const BROWN_LIGHT_COLOR   = '#E2CFBE'
export const GRAY_COLOR          = '#747579'
export const GRAY_LIGHT_COLOR    = 'rgba(115, 116, 120, 0.6)'
export const WHITE_COLOR         = '#FFFFFF'
export const BLACK_COLOR         = '#000000'
export const RED_COLOR           = '#FF0000'
