import Head from 'next/head'
import NextLink from 'next/link'

import { Raleway } from "next/font/google"
const RalewayFont = Raleway({
    weight: ['300', '400', '500', '700', '900'],
    style: ['normal', 'italic'],
    subsets: ['latin']
})

export default function Home() {

    return (
        <>
            <Head>
                <title>Yolo Style</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`container ${RalewayFont.className}`}>
                <NextLink href={'#'}>Hola Mundo!</NextLink>
                <h1>Yolo Style</h1>
            </main>
        </>
    )
}
